### ISSUE TITLE
Missing "apiserver" restart instruction

### ISSUE THREAD

**Issue by AAhmed84** [Azure/kubernetes-kms#30]
Hi,

The documentation here https://github.com/Azure/kubernetes-kms/blob/master/manual-install.md has step-7 to restart "apiserver" but the instructions are missing on how to restart "apiserver" in azure kubernetes.

Thanks

**Comment by ritazh** [comment]
@AAhmed84 you can restart apiserver by deleting the apiserver pod. The pod will then be recreated.

For example:
`kubectl delete pod kube-apiserver-k8s-master-16237184-0 -n kube-system`

**Comment by AAhmed84** [comment]
@ritazh I do not have this pod in my kube-system namespace. Please see attached screenshot.
Thanks
<img width="696" alt="screen shot 2018-07-12 at 18 34 36" src="https://user-images.githubusercontent.com/13121841/42649757-6e0b995c-8602-11e8-9e48-8c642f0881ae.png">

**Comment by ritazh** [comment]
@AAhmed84 seems you are on an AKS cluster not acs-engine. The manual steps are just for acs-engine since you need to be on the master nodes to execute those steps. (will update this in the doc to make it more clear)

AKS support is coming. In the meantime, you can use acs-engine. Follow this [doc](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/features.md#azure-key-vault-data-encryption) to create a cluster with KMS already enabled.

**Comment by AAhmed84** [comment]
@ritazh Thank you for your help.
