### ISSUE TITLE
[Question] Will this be replacing the SP visibility in azure.json

### ISSUE THREAD

**Issue by djsly** [Azure/kubernetes-kms#6]
Hello from reading the documentation, I can see that there will be 3 new flags in the azure.json. 

I'm wondering if those will be replacing the SP clientID and secret that we are currently dropping in the json file.

thanks!

**Comment by ritazh** [comment]
👋 @djsly No the SP flags will remain in azure.json. We are really introducing 2 new flags. keyVersion is optional.

**Comment by djsly** [comment]
Thanks! Do you know which project is suppose to secure the SP secret away from the azure.json ?
@khenidak  maybe ?

**Comment by khenidak** [comment]
Currently you can do MSI, where the cluster uses the node identity (no secrets in `azure.json`). We are also working on explicitly assigned managed identity. we put a hold on the PR because the feature is still in private preview https://github.com/Azure/azure-sdk-for-ruby/pull/1170 -- we will merge once the feature goes public preview.

**Comment by khenidak** [comment]
@kkmsft is owns the "EMSI" feature. just FYI

**Comment by djsly** [comment]
Thanks all for the inputs. Once the azure-sdk-for-ruby is merged, where would be the next PR to bring the support to Kubernetes? (Upstream?)

**Comment by khenidak** [comment]
I am not sure i understand this question - can you please expand on it?

**Comment by djsly** [comment]
> Currently you can do MSI

This is ACS-engine specific right? If not, my bad, I will have a closer look. If you have a Document on how to puse MSI with upstream, that would be appreciated. 

thanks @khenidak
